/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC - https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 *
 * XChain Indexer - Genesis State Dump / Import
 *
 * The genesis ledger bootstrap (genesis.js) derives Counterparty/Dogeparty name
 * ownership by replaying ~240k synthetic ISSUE/TRANSFER actions through the full
 * pipeline. That derivation is identical on every node and takes ~1 hour on the
 * BTC manifest, yet a node doing a trustless full parse must do it before it can
 * process block GENESIS_BLOCK+1. This module precomputes that work ONCE into a
 * portable artifact: the exact post-injection database rows, which a full-parse
 * node bulk-imports in minutes instead of re-deriving.
 *
 * Consensus safety: the dump captures the literal rows (with explicit ids and
 * action indexes) a canonical injection produced, so re-importing them verbatim
 * reproduces byte-identical state and therefore byte-identical genesis block
 * hashes. The artifact is pinned by the sha256 of its UNCOMPRESSED content
 * (gzip is transport only; gzip bytes are not stable across zlib versions), and
 * the importer recomputes the genesis block hashes after loading and refuses to
 * proceed unless they equal the hashes recorded in the dump. Trust therefore
 * reduces to the pinned GENESIS_DUMP_HASH, exactly like GENESIS_LEDGER_HASH for
 * the CSV path. An import-vs-inject hash-identity test guards equivalence.
 *
 * File format (NDJSON, gzip-wrapped on disk):
 *   line 1  : {"meta": {version, coin, genesisBlock, expectedHashes, tableOrder, rowCounts}}
 *   per table: {"t": "<table>", "cols": ["c1","c2",...]}   then one {"r":[v1,v2,...]} per row
 * Values are JSON scalars (Number|string|null); BIGINT columns arrive as Numbers
 * (pool bigIntAsNumber=true) and stay within Number.MAX_SAFE_INTEGER.
 *
 ********************************************************************/

const fs     = require('fs');
const zlib   = require('zlib');
const crypto = require('crypto');
const readline = require('readline');

// Tables the dump never carries. `blocks` is regenerated by the normal createBlock
// after import (its hashes are recomputed from the imported rows, which doubles as
// the load-integrity check). `index_fiats` is the only schema-seeded table, so the
// fresh import target already holds it; re-inserting would collide.
const EXCLUDE_TABLES = new Set(['blocks', 'index_fiats']);

// Rows per multi-row INSERT during import. ~500 rows x a dozen columns stays well
// under the placeholder limit while keeping round-trips low.
const IMPORT_BATCH = 500;

class GenesisDump {

    constructor(db, util, config){
        this.db     = db;
        this.util   = util;
        this.config = config;
    }

    // --- generation -------------------------------------------------------------
    // Write the current (post-injection, pre-createBlock) genesis state to `file`.
    // Returns { contentHash, rowCounts, expectedHashes }. Run this from the generator
    // script after a CSV inject, BEFORE createBlock, so the dump is pure inject output.
    async write(file){
        let genesisBlock = Number(this.config['GENESIS_BLOCK']);
        let expectedHashes = await this._blockHashes(genesisBlock);

        // Discover the non-empty, non-excluded tables to carry.
        let tables = [];
        let rowCounts = {};
        let allTables = (await this.db.doQuery('SHOW TABLES')).map(r => Object.values(r)[0]);
        for(let t of allTables){
            if(EXCLUDE_TABLES.has(t))
                continue;
            let c = await this.db.doQuery('SELECT COUNT(*) AS c FROM `' + t + '`');
            let n = (c.length > 0) ? Number(c[0].c) : 0;
            if(n > 0){
                tables.push(t);
                rowCounts[t] = n;
            }
        }
        tables.sort(); // deterministic table order -> deterministic content bytes

        // Stream: hash the UNCOMPRESSED content as we write, gzip to disk.
        let hash = crypto.createHash('sha256');
        let gzip = zlib.createGzip({ level: 9 });
        let out  = fs.createWriteStream(file);
        gzip.pipe(out);
        const writeLine = (obj) => {
            let line = JSON.stringify(obj) + '\n';
            hash.update(line);
            return gzip.write(line) ? Promise.resolve() : new Promise(res => gzip.once('drain', res));
        };

        await writeLine({ meta: {
            version: 1, coin: this.config['COIN'], genesisBlock,
            expectedHashes, tableOrder: tables, rowCounts
        }});

        for(let t of tables){
            // Column order from the table definition; reused verbatim on import.
            let cols = (await this.db.doQuery('SHOW COLUMNS FROM `' + t + '`')).map(r => r.Field);
            await writeLine({ t, cols });
            // Stream rows ordered by the table's primary/first column for stable bytes.
            // Every dumped table has a deterministic first column (id / action_index /
            // tx_index) so ORDER BY 1 yields the same byte stream on every generation.
            let colList = cols.map(c => '`' + c + '`').join(',');
            let rows = await this.db.doQuery('SELECT ' + colList + ' FROM `' + t + '` ORDER BY 1 ASC');
            for(let row of rows)
                await writeLine({ r: cols.map(c => this._scalar(row[c])) });
        }

        await new Promise((res, rej) => { gzip.end(); out.on('finish', res); out.on('error', rej); });
        let contentHash = hash.digest('hex');
        return { contentHash, rowCounts, expectedHashes };
    }

    // --- import -----------------------------------------------------------------
    // Bulk-load a dump into the (fresh) indexer DB. Verifies the pinned content hash
    // (GENESIS_DUMP_HASH) while streaming, loads every table, then recomputes the
    // genesis block hashes and asserts they equal the dump's recorded expected hashes.
    // Throws (halting the node) on any mismatch. Returns { rowsImported, expectedHashes }.
    async read(file){
        let pinned = this.config['GENESIS_DUMP_HASH'];

        // Verify-then-import. When a content hash is pinned, prove the artifact
        // matches it BEFORE a single row touches the DB. This makes "trust
        // reduces to the pinned GENESIS_DUMP_HASH" literal: a tampered dump is
        // rejected up front and never reaches the insert path (so it can neither
        // do DB work nor exercise the identifier handling below). Previously the
        // content hash was checked only AFTER streaming every row into the block
        // transaction, leaving safety resting entirely on that transaction
        // rolling back. Unpinned dev/regtest dumps (no pin) skip this gate and
        // rely on the post-import block-hash recompute as their only check.
        if(!this.util.isNull(pinned)){
            let fileHash = await this._hashFile(file);
            if(fileHash !== String(pinned).toLowerCase()){
                console.error('GENESIS FATAL: dump content hash mismatch for ' + file +
                    ' (expected ' + pinned + ', got ' + fileHash + '). Halting.');
                throw new Error('Genesis dump hash mismatch');
            }
        }

        let meta   = null;
        let curTable = null, curCols = null, batch = [], rowsImported = 0;

        const flush = async () => {
            if(curTable === null || batch.length === 0)
                return;
            await this._insertBatch(curTable, curCols, batch);
            rowsImported += batch.length;
            batch = [];
        };

        let gunzip = zlib.createGunzip();
        fs.createReadStream(file).pipe(gunzip);
        let rl = readline.createInterface({ input: gunzip, crlfDelay: Infinity });
        for await (let line of rl){
            if(line === '')
                continue;
            let obj = JSON.parse(line);
            if(obj.meta){ meta = obj.meta; continue; }
            if(obj.t){
                await flush();
                // Table + column names are interpolated into SQL (identifiers
                // can't be parameterized), so validate their shape before use.
                // Every real indexer identifier is a bare [A-Za-z0-9_] name; a
                // backtick/space/paren/semicolon is an injection attempt.
                this._assertIdentifier(obj.t);
                if(!Array.isArray(obj.cols) || obj.cols.length === 0)
                    throw new Error('Genesis dump table header missing columns: ' + obj.t);
                for(let c of obj.cols)
                    this._assertIdentifier(c);
                curTable = obj.t; curCols = obj.cols;
                continue;
            }
            if(obj.r){
                // A row before any table header is a malformed dump. Refuse it
                // rather than buffering rows that flush() would silently drop
                // (an attacker could otherwise grow `batch` without bound -> OOM).
                if(curTable === null)
                    throw new Error('Genesis dump row before any table header: ' + file);
                batch.push(obj.r);
                if(batch.length >= IMPORT_BATCH)
                    await flush();
            }
        }
        await flush();

        if(meta === null)
            throw new Error('Genesis dump missing meta header: ' + file);
        // The dump pins the rows to the block it was generated at; importing them at a
        // different GENESIS_BLOCK would leave block_index out of step with createBlock.
        if(Number(meta.genesisBlock) !== Number(this.config['GENESIS_BLOCK']))
            throw new Error('Genesis dump block ' + meta.genesisBlock + ' != configured GENESIS_BLOCK ' + this.config['GENESIS_BLOCK']);

        // Load-integrity + consensus check: recompute the genesis block hashes from the
        // imported rows and require they equal what the dump recorded. Catches a truncated
        // or partial import and any drift between the dump and this node's hasher.
        let got = await this._blockHashes(meta.genesisBlock);
        for(let k of ['ledger', 'actions', 'state', 'contracts']){
            if(got[k] !== meta.expectedHashes[k]){
                console.error('GENESIS FATAL: imported ' + k + ' hash ' + got[k] +
                    ' != dump expected ' + meta.expectedHashes[k] + '. Halting.');
                throw new Error('Genesis dump hash verification failed (' + k + ')');
            }
        }
        return { rowsImported, expectedHashes: meta.expectedHashes };
    }

    // --- helpers ----------------------------------------------------------------

    // sha256 of the artifact's UNCOMPRESSED content, streamed (constant memory).
    // The writer hashes the exact line strings it feeds to gzip, so the sum of
    // those bytes equals the raw gunzip output hashed here; this reproduces the
    // `write()` contentHash / pinned GENESIS_DUMP_HASH without parsing the dump.
    // (A verify pass and a later import pass read the file twice; a live disk
    // swap between them is out of scope, matching the local one-shot threat model.)
    async _hashFile(file){
        let hash   = crypto.createHash('sha256');
        let stream = fs.createReadStream(file).pipe(zlib.createGunzip());
        for await (let chunk of stream)
            hash.update(chunk);
        return hash.digest('hex');
    }

    // Reject any table/column identifier from the (untrusted) dump that is not a
    // bare [A-Za-z0-9_] name. Identifiers are interpolated into SQL and cannot be
    // parameterized, so shape validation is the guard against identifier injection.
    _assertIdentifier(name){
        if(typeof name !== 'string' || !/^[A-Za-z0-9_]+$/.test(name))
            throw new Error('Genesis dump has an invalid SQL identifier: ' + JSON.stringify(name));
    }

    // Recompute the four genesis block hashes as plain strings (the shape stored in
    // the dump). Works pre-createBlock since getBlockHashes derives from the block's
    // own rows, not the blocks row.
    async _blockHashes(genesisBlock){
        let h = await this.db.getBlockHashes(genesisBlock);
        return { ledger: h.ledger.hash, actions: h.actions.hash, state: h.state.hash, contracts: h.contracts.hash };
    }

    // Multi-row parameterized INSERT for one table. Values are parameterized;
    // the table + column identifiers cannot be, so re-assert their shape here
    // (read() already validates, but keep the guard with the SQL-building site).
    async _insertBatch(table, cols, rows){
        this._assertIdentifier(table);
        for(let c of cols)
            this._assertIdentifier(c);
        let colList = cols.map(c => '`' + c + '`').join(',');
        let one     = '(' + cols.map(() => '?').join(',') + ')';
        let sql     = 'INSERT INTO `' + table + '` (' + colList + ') VALUES ' + rows.map(() => one).join(',');
        let args    = [];
        for(let r of rows)
            for(let v of r)
                args.push(v);
        await this.db.doQuery(sql, args);
    }

    // Normalize a DB value for JSON. bigIntAsNumber=true means BIGINTs are Numbers;
    // a stray BigInt (future driver change) is stringified so JSON.stringify cannot throw.
    _scalar(v){
        if(v === undefined || v === null) return null;
        if(typeof v === 'bigint')         return Number(v);
        return v;
    }
}

module.exports = GenesisDump;
